### 소프트맥스를 이용한 다중분류 로지스틱 회귀 모델
M개의 입력을 받아 N개의 클래스로 출력하는 로지스틱 회귀 모델  
다중 분류 로지스틱 회귀 모델을 소프트맥스라고 부름  
케라스에서 제공하는 MNIST 데이터를 이용 0 ~ 9 까지 분류   

In [1]:
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.utils import to_categorical
from keras.datasets import mnist
import numpy as np


In [2]:
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 2s 0us/step


In [3]:
# 손글씨 데이터 28 X 28, X_train 에는 60000개 데이터, X_test 에는 10000개의 데이터가 있슴.

In [4]:
print('train data (count, row, colum) : ' + str(X_train.shape))
print('test data (count, row, colum) : ' + str(X_test.shape))

train data (count, row, colum) : (60000, 28, 28)
test data (count, row, colum) : (10000, 28, 28)


In [5]:
# 하나 샘플 보기
print(X_train[0])

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   3  18  18  18 126 136
  175  26 166 255 247 127   0   0   0   0]
 [  0   0   0   0   0   0   0   0  30  36  94 154 170 253 253 253 253 253
  225 172 253 242 195  64   0   0   0   0]
 [  0   0   0   0   0   0   0  49 238 253 253 253 253 253 253 253 253 251
   93  82  82  56  39   0   0   0   0   0]
 [  0   0   0   0   0   0   0  18 219 253 253 253 253 253 198 18

In [6]:
print('sample from train : ' + str(y_train[0]))
print('sample from test : ' + str(y_test[0]))

sample from train : 5
sample from test : 7


In [8]:
# 28 * 28 픽셀의 데이터를 행과 열 구분 없이 784길이의 배열로 구조 단순화
input_dim = 784 # 28 * 28
X_train = X_train.reshape(60000, input_dim)
X_test =  X_test.reshape(10000, input_dim)

In [9]:
print(X_train.shape)

(60000, 784)


In [10]:
print(X_test.shape)

(10000, 784)


In [11]:
# 학습 시 y값과의 cross entropy를 측정 하기위해 y를 one hot encoding 변환
num_classes = 10
y_train = to_categorical(y_train, num_classes)
y_test = to_categorical(y_test, num_classes)

In [12]:
print(y_train[0])

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


In [13]:
# 소프트 맥스 구현
# 784 (28 * 28)개의 입력을 받아서 10개의 시그모이드 값을 출력
model = Sequential()
model.add(Dense(input_dim=input_dim, units = 10, activation='softmax'))

In [14]:
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(X_train, y_train, batch_size=2048, epochs=100, verbose=0)

In [22]:
score = model.evaluate(X_test, y_test)
print('Test accuarcy : ' , score[0])

10000/10000 [==============================] - 0s 10us/step
Test accuarcy :  0.8959000110626221


In [25]:
help(model.evaluate)

Help on method evaluate in module keras.engine.training:

evaluate(x=None, y=None, batch_size=None, verbose=1, sample_weight=None, steps=None, callbacks=None, max_queue_size=10, workers=1, use_multiprocessing=False) method of keras.engine.sequential.Sequential instance
    Returns the loss value & metrics values for the model in test mode.
    
    Computation is done in batches.
    
    # Arguments
        x: Input data. It could be:
            - A Numpy array (or array-like), or a list of arrays
              (in case the model has multiple inputs).
            - A dict mapping input names to the corresponding
              array/tensors, if the model has named inputs.
            - A generator or `keras.utils.Sequence` returning
              `(inputs, targets)` or `(inputs, targets, sample weights)`.
            - None (default) if feeding from framework-native
              tensors (e.g. TensorFlow data tensors).
        y: Target data. Like the input data `x`,
            it co

In [19]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 10)                7850      
Total params: 7,850
Trainable params: 7,850
Non-trainable params: 0
_________________________________________________________________


In [20]:
model.layers[0].weights

[<tf.Variable 'dense_1/kernel:0' shape=(784, 10) dtype=float32, numpy=
 array([[ 0.08436174,  0.03863066,  0.0442848 , ..., -0.0404053 ,
          0.07200589, -0.05049599],
        [-0.04589039,  0.00770389,  0.06045688, ..., -0.01048061,
          0.03353363,  0.06947581],
        [ 0.0079003 ,  0.01624976, -0.07962542, ...,  0.07176239,
         -0.06685612,  0.08466499],
        ...,
        [ 0.06001914, -0.02697768,  0.04727211, ...,  0.01053727,
          0.07452012, -0.06087647],
        [ 0.00812294,  0.04260286,  0.00695644, ..., -0.04767902,
          0.05279385, -0.03739933],
        [ 0.05845838, -0.01514399, -0.06050745, ..., -0.04884383,
         -0.04145357, -0.06853745]], dtype=float32)>,
 <tf.Variable 'dense_1/bias:0' shape=(10,) dtype=float32, numpy=
 array([-0.01169908,  0.01229555,  0.02639327, -0.01007401,  0.00171401,
         0.09326721, -0.00013407,  0.03056818, -0.11880752, -0.02352336],
       dtype=float32)>]